name: Units Tests

on: [push, pull_request]

jobs:
  own_tester:
    name: Own Tester
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Progs for Tester
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt update
          sudo apt install -y bash clang valgrind

      - name: Environnement Informations Linux
        if: matrix.os == 'ubuntu-latest'
        run: |
          echo OS version
          lsb_release -a
          echo
          echo Linux kernel version
          uname -r
          echo
          echo Clang version
          clang++ --version
          echo
          echo Valgrind version
          valgrind --version
        shell: bash

      - name: Environnement Informations macOS
        if: matrix.os == 'macos-latest'
        run: |
          echo OS version
          system_profiler SPSoftwareDataType
          echo
          echo Clang version
          clang++ --version

      - name: Launch Own test Vector
        run: ./vector_test.sh
        shell: bash

      - name: Launch Own test Vector with Capacity check
        if: matrix.os == 'ubuntu-latest'
        run: ./vector_test.sh capacity
        shell: bash
        continue-on-error: true

      - name: Launch Own test Map
        run: ./map_test.sh
        shell: bash

  third_party_tester:
    name: Third party tester
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Install Progs for Tester
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt update
          sudo apt install -y bash clang valgrind

      - name: Environnement Informations Linux
        if: matrix.os == 'ubuntu-latest'
        run: |
          echo OS version
          lsb_release -a
          echo
          echo Linux kernel version
          uname -r
          echo
          echo Clang version
          clang++ --version
          echo
          echo Valgrind version
          valgrind --version
          echo
          echo DiffUtils version
          diff --version
        shell: bash

      - name: Environnement Informations macOS
        if: matrix.os == 'macos-latest'
        run: |
          echo OS version
          system_profiler SPSoftwareDataType
          echo
          echo Clang version
          clang++ --version
          echo
          echo DiffUtils version
          diff --version
        shell: bash

      - name: Launch Script
        run: cd containers_test && ./do.sh vector stack map
        shell: bash
        continue-on-error: true
